apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nginx
  name: local-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
